// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCentJJ6YztJu_Ro3HjmtZ26Nco6P_M-rY',
    appId: '1:70716772881:web:e2ea419a5934068f9517b0',
    messagingSenderId: '70716772881',
    projectId: 'myuniquefunfun',
    authDomain: 'myuniquefunfun.firebaseapp.com',
    storageBucket: 'myuniquefunfun.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBYx2HG919mTk4gyBWvWhdKHaeDu3oWVa4',
    appId: '1:70716772881:android:af9116b8cca246509517b0',
    messagingSenderId: '70716772881',
    projectId: 'myuniquefunfun',
    storageBucket: 'myuniquefunfun.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDsN_IM_pJ1lPmQhaVH4T1NMbR4YRO-pNs',
    appId: '1:70716772881:ios:c0e4068d895f153f9517b0',
    messagingSenderId: '70716772881',
    projectId: 'myuniquefunfun',
    storageBucket: 'myuniquefunfun.appspot.com',
    iosClientId: '70716772881-ogeq1n6s02nic4ufcb3kosh02ep2fb5o.apps.googleusercontent.com',
    iosBundleId: 'com.example.myuniquefunfun',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDsN_IM_pJ1lPmQhaVH4T1NMbR4YRO-pNs',
    appId: '1:70716772881:ios:4d7b1a97b4defdb39517b0',
    messagingSenderId: '70716772881',
    projectId: 'myuniquefunfun',
    storageBucket: 'myuniquefunfun.appspot.com',
    iosClientId: '70716772881-2f8a006rds0crf6u2fn6g311pbgi34lf.apps.googleusercontent.com',
    iosBundleId: 'com.example.myuniquefunfun.RunnerTests',
  );
}
